# Generated by Django 4.1.2 on 2022-10-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checho', '0002_alter_citas_cliente_alter_citas_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='foto',
            field=models.ImageField(default='checho/fotos/default.png', upload_to='checho/fotos'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(default='checho/fotos/default.png', upload_to='checho/fotos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='foto',
            field=models.ImageField(default='checho/fotos/default.png', upload_to='checho/fotos'),
        ),
    ]
